Repository the-difference-engine/ymim, pull requests merged in 2019-07, with the labels that each got.

#138 "Contact" page layout & design
  frontend/package-lock.json
  frontend/src/components/static_pages/contact.css
  frontend/src/components/static_pages/contact.jsx
Labels: CR: Changes Requested

#153 feature/149/fix-footer-routing
  frontend/src/components/common/footer/index.css
  frontend/src/components/common/footer/index.jsx
Labels: CR: Needs Review

#141 Single Carousel component for static page splash images
  frontend/src/components/Single_Carousel/Single_Carousel.js
  frontend/src/components/Single_Carousel/index.css
  frontend/src/components/enroll/index.js
  frontend/src/components/static_pages/about.jsx
  frontend/src/index.css
  package-lock.json
Labels: CR: Needs Review

#162 Feature/158/nav bar and enroll link
  frontend/package-lock.json
  frontend/src/components/SingleCarousel/SingleCarousel.js
  frontend/src/components/SingleCarousel/index.css
  frontend/src/components/common/footer/index.jsx
  frontend/src/components/common/header/index.css
  frontend/src/components/common/header/navbar.jsx
  frontend/src/components/enroll/index.js
  frontend/src/components/static_pages/about.jsx
  frontend/src/index.css
Labels: CR: Needs Review

#161 Footer social icons
  frontend/src/components/common/footer/index.css
  frontend/src/components/common/footer/index.jsx
Labels: CR: Needs Review, frontend

#170 Redirect and scroll to the top of the page
  frontend/src/components/common/footer/index.jsx
  frontend/src/components/to_the_top.jsx
  frontend/src/router.js
Labels: CR: Needs Review

#160 Feature/131/mid section refactor
  backend/events/management/commands/create_test_events.py
  backend/profiles/management/commands/create_test_users.py
  frontend/src/components/home/midsection/lower_mid.jsx
  frontend/src/components/home/midsection/mid.css
  frontend/src/components/home/midsection/upper_mid.jsx
  frontend/src/components/to_the_top.jsx
Labels: CR: Needs Review, frontend

#169 Add files via upload
  frontend/src/assets/Pierre-Priestley_profile.jpg
  frontend/src/assets/Shirley-Scott_profile .jpg
Labels: CR: Needs Review

#147 Feature/140/meet the team
  frontend/public/images/calix.jpg
  frontend/public/images/donation.jpg
  frontend/public/images/dream_team.jpg
  frontend/public/images/jm_mw_ep.jpg
  frontend/src/components/common/footer/index.jsx
  frontend/src/components/static_pages/team.jsx
  frontend/src/index.css
Labels: CR: Needs Review

#175 Eventbright API proof of concept
  frontend/package-lock.json
  frontend/src/actions/events.js
  frontend/src/components/admin/index.jsx
  frontend/src/components/events/event_card.jsx
  frontend/src/components/events/event_form.jsx
  frontend/src/components/events/index.css
  frontend/src/components/events/index.jsx
  frontend/src/reducers/events.js
Labels: CR: Needs Review
